# Generated by Django 4.2.6 on 2023-10-06 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.bankuser')),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='authentication.bankaccount')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reciever', to='authentication.wallet')),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reciever', to='authentication.bankaccount')),
            ],
            options={
                'db_table': 'bank_transaction',
            },
        ),
    ]
