# Generated by Django 4.2.6 on 2023-10-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_bankaccount_wallet_wallettransaction_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='type',
            field=models.CharField(choices=[('SEND', 'Send'), ('RECIEVED', 'Recieved')], default='SEND', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='wallet',
            field=models.OneToOneField(default='a84d4974-0a79-4258-a024-c1d6d8cd321f', on_delete=django.db.models.deletion.CASCADE, related_name='user_bank', to='authentication.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('SEND', 'Send'), ('RECIEVED', 'Recieved')], default='SEND', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.OneToOneField(default='a84d4974-0a79-4258-a024-c1d6d8cd321f', on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='authentication.wallet'),
            preserve_default=False,
        ),
    ]
