# Generated by Django 4.2.6 on 2023-10-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_banktransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='password',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
