# Generated by Django 4.2.6 on 2023-10-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bankaccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='sender',
            field=models.OneToOneField(default='a84d4974-0a79-4258-a024-c1d6d8cd321f', on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank', to='authentication.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender',
            field=models.OneToOneField(default='a84d4974-0a79-4258-a024-c1d6d8cd321f', on_delete=django.db.models.deletion.CASCADE, related_name='sender_wallet', to='authentication.wallet'),
            preserve_default=False,
        ),
    ]
