# Generated by Django 4.2.6 on 2023-10-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_banktransaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reciever', to='authentication.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank', to='authentication.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reciever', to='authentication.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_wallet', to='authentication.wallet'),
        ),
    ]
